version: 0.0
os: linux
files:
  - source: /
    destination: /flask-app
permissions:
   - object: /flask-app/startApp.sh
     mode: 777
hooks:
   ApplicationStart:
     - location: /flask-app/startApp.sh
       timeout: 30
